export const STRINGS = {
  trigger: "Filters",
  title: "Advanced Search Filters",
  sets: "Sets",
  set: "Set",
  relations: "Relations",
  relation: "Relation",
  addFilter: "add filter",
  removeFilter: "remove filter",
  addNWRSet: "add NWR set",
  addClusterSet: "add cluster set",
  nwrLabel: "NWR",
  clusterLabel: "Cluster",
  removeSet: "remove set",
  operatorEquals: "equals",
  operatorGreater: "greater than",
  operatorLess: "less than",
  operatorContains: "contains",
  addRelationDistance: "add distance relation",
  addRelationContains: "add contains relation",
  containsLabel: "contains",
  distanceLabel: "away from",
  tooltipOperator: "Operator",
  tooltipKey: "OSM Key",
  tooltipValue: "OSM Value",
  typeDistance: "Distance",
  typeContains: "Contains",
};
